- name: Instalando PHP-FPM...
  apt:
    name: php-fpm

- name: Copiando info.php en cada Document Root...
  copy:
    src: info.php
    dest: "{{ item.datos.documentroot }}/info.php"
    owner: www-data
    group: www-data
    mode: u+rw,g+r,o+r
  with_items:
    - "{{ virtualhosts_on }}"
